name:                sql2er
version:             0.1.0.0
github:              "tusharad/sql2er"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2024 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A CLI tool that converts Postgres SQL file to ER-digram.
category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tusharad/sql2er#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- diagrams-lib
- diagrams-svg
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - ImportQualifiedPost

executables:
  sql2er-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sql2er

tests:
  sql2er-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
      - ImportQualifiedPost
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sql2er
    - megaparsec
    - text
    - tasty
    - tasty-hunit
