name: test fixed cabal

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish Package and Haddock Docs to Hackage (curl ${{ matrix.curl_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        curl_version: ['7.68.0', '7.81.0', '8.0.1', '8.4.0', '8.5.0', '8.10.1', '8.12.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2

      - name: Install specific curl version (${{ matrix.curl_version }})
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libnghttp2-dev libzstd-dev wget
          wget https://curl.se/download/curl-${{ matrix.curl_version }}.tar.gz
          tar -xzf curl-${{ matrix.curl_version }}.tar.gz
          cd curl-${{ matrix.curl_version }}
          ./configure --prefix=/usr/local --with-ssl --with-nghttp2
          make -j$(nproc)
          sudo make install
          sudo ldconfig
          curl --version

      - name: Install cabal
        run: |
          git clone https://github.com/tusharad/cabal.git
          cd cabal
          git checkout fix/cabal-upload-fail
          cabal --version
          cabal install --project-file=cabal.release.project cabal-install
          cabal --version

      - name: Verify package checks & tests
        run: |
          cabal check
          cabal test
      - name: Build Source Distribution Tarball
        run: |
          cabal sdist
      - name: Build Haddock Documentation Tarball for Hackage
        run: |
          cabal haddock --haddock-for-hackage --enable-doc
      - name: Upload Package to Hackage
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
        run: |
          SDIST_FILE=$(ls dist-newstyle/sdist/sql2er-*.tar.gz | head -n 1)
          echo "Publishing package ${SDIST_FILE} to Hackage..."
          cabal upload -u "${HACKAGE_USERNAME}" -p "${HACKAGE_PASSWORD}" "${SDIST_FILE}"
      - name: Upload Haddock Documentation to Hackage
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
        run: |
          DOCS_FILE=$(ls dist-newstyle/sql2er-*-docs.tar.gz | head -n 1)
          echo "Publishing Haddock documentation ${DOCS_FILE} to Hackage..."
          cabal upload --documentation -u "${HACKAGE_USERNAME}" -p "${HACKAGE_PASSWORD}" "${DOCS_FILE}"
